name: Build Flutter Windows App

on:
  push:
    branches:
      - main
  workflow_dispatch: # əl ilə də işə sala bilirsən

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7' # Sənin istifadə etdiyin Flutter versiyasını yaz

      - name: Enable Windows
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows --release

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: student_management_windows
          path: build/windows/runner/Release
